[tool.poetry]
name = "backup2disk"
version = "0.1.0"
description = ""
authors = ["Willians Patiño <ppwj@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
rsync-system-backup = "^1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
